---
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args:
          - --maxkb=4096
      - id: check-builtin-literals
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: mixed-line-ending
      - id: detect-private-key
      - id: pretty-format-json
      - id: detect-aws-credentials
      - id: check-case-conflict
      - id: fix-byte-order-marker
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages: [pre-commit]
